[project]
name = "mymodule"
version = "0.3.10"
description = "generic description for generic module"
authors = [{ name = "Diego Reiriz Cores", email = "dreiriz@gradiant.org" }]
dependencies = [
    "click<9.0.0,>=8.1.7",
    "SQLAlchemy<3.0.0,>=2.0.23",
    "fastapi<1.0.0,>=0.104.1",
    "psycopg2-binary<3.0.0,>=2.9.9",
    "pydantic-settings<3.0.0,>=2.1.0",
]
requires-python = "==3.11.*"
readme = "README.md"

[dependency-groups]
dev = [
    "black>=25.1.0",
    "flake8>=7.3.0",
    "isort>=5.12.0",
    "pre-commit>=4.2.0",
    "pylint>=3.3.7",
]
test = ["pytest>=7.4.2", "pytest-cov>=4.1.0"]

[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
log_cli = true
log_level = "DEBUG"
